version: '3.7'

services:
  app:
    build:
      dockerfile: .docker/php-fpm/Dockerfile
      context: .
    restart: unless-stopped
    container_name: wp-cli
    tty: true
    env_file: .env
    environment:
      DB_CONNECTION: ${APP_DB_CONNECTION}
      DB_HOST: ${APP_DB_HOST}
      DB_PORT: ${APP_DB_PORT}
      DB_DATABASE: ${APP_DB_DATABASE}
      DB_USERNAME: ${APP_DB_USERNAME}
      DB_PASSWORD: ${APP_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${COMPOSE_PROJECT_NAME}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      WORDPRESS_DB_HOST: ${APP_DB_HOST}
      WORDPRESS_DB_USER: ${APP_DB_DATABASE}
      WORDPRESS_DB_PASSWORD: ${APP_DB_PASSWORD}
    volumes:
      - ./wp:/var/www/html
    networks:
      - soares_net
  nginx:
    image: nginx:1.19.0-alpine
    restart: unless-stopped
    tty: true
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./wp:/var/www/html
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./.docker/nginx/ssl/:/etc/nginx/ssl/
    networks:
      - soares_net

  mariadb:
    image: "mariadb:${MARIADB_VERSION}"
    restart: 'always'
    container_name: base
    ports:
    - 3306:3306
    volumes:
      - /var/lib/mysql/data:${MARIADB_DATA_DIR}
      - /var/lib/mysql/logs:${MARIADB_LOG_DIR}
      - /var/docker/mariadb/conf:/etc/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - soares_net

networks:
  soares_net:
    driver: bridge